export default function() {
  return[
    {
      title:'LoremIspsum1'
    },{
      title:'LoremIspsum2'
    },{
      title:'LoremIspsum3'
    },{
      title:'LoremIspsum4'
    },{
      title:'LoremIspsum5'
    },{
      title:'LoremIspsum6'
    },{
      title:'LoremIspsum7'
    }
  ]
}
